### ISSUE TITLE
Problems encountered while running the project

### ISSUE THREAD

**Issue by liuqianqian-x** [nolanwagener/safe_rl#3]
Excuse me, “AttributeError: module 'safe_rl' has no attribute 'cppo_pytorch' ” when executing command line“ python -m safe_rl.run cppo”, as shown in the figure, can you tell me how to solve it? Thanks.
![Screenshot of the problem](https://user-images.githubusercontent.com/74896542/128672542-e182a203-64f1-4672-895d-1666c767872f.png)

**Comment by nolanwagener** [comment]
Hi @liuqianqian-x, sorry that you're running into this issue. We do not use the `run.py` script for our experiments. Instead we directly call the algorithm file (in your case, `cppo.py`) and pass in the necessary arguments. Please refer to this bash script as an example: https://github.com/nolanwagener/safe_rl/blob/icml/scripts/point/script.sh

**Comment by liuqianqian-x** [comment]
Thank you for your reply and help, I've tried as you said, but it seems that some files are missing here, as shown below. So could you please update the complete code or tell me how to solve it next? Thank you very much.
![1628581132(1)](https://user-images.githubusercontent.com/74896542/128827625-4da52aa0-8029-491d-874c-92591913b11e.png)

**Comment by nolanwagener** [comment]
The `__main__` function in CPPO is actually unused (and I just removed it to avoid confusion). The Python script to refer to is here: https://github.com/nolanwagener/safe_rl/blob/icml/scripts/point/cppo.py
