### ISSUE TITLE
how to reproduce the baseline CPO?

### ISSUE THREAD

**Issue by hlhang9527** [nolanwagener/safe_rl#6]
Dear author,

I'm trying to reproduce your experiment result but find no CPO implementation in scripts.sh, could you please tell me which line is the implementation of the baseline CPO or do I need to reproduce the CPO myself? Thanks.

**Comment by nolanwagener** [comment]
I used the safety-starter-agents implementation of CPO https://github.com/openai/safety-starter-agents

For example, for the point environment, within `safety-starter-agents/safe_rl/pg` I ran
```bash
python run_agent.py --env extra_envs:Point-v0 --cost_lim 0.01 --agent cpo --epoch 500 --seed [SEED]
```

**Comment by hlhang9527** [comment]
Thanks!
